amos/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

import meteors.urls
import stations.urls
import stations.views
import core.urls
import accounts.urls

urlpatterns = [
    path('admin/',      admin.site.urls),
    path('api-auth/',   include('rest_framework.urls')),

    path('about/',      include(core.urls)),
    path('',            include(meteors.urls)),
    path('',            include(stations.urls)),

    path('accounts/',   include(accounts.urls)),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)          # THIS IS FOR DEVELOPMENT ONLY

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

stations/urls.py
from django.urls import include, path
from django.views.decorators.csrf import csrf_exempt

from .views import station, subnetwork, heartbeat

urlpatterns = [
    path(
        '',
        subnetwork.StatusView.as_view(),
        name='status'
    ),
    path(
        'stations/',
        subnetwork.StatusView.as_view(),
        name='status'
    ),

    path(
        'station/<slug:code>/',
        station.DetailView.as_view(),
        name='station'
    ),
    path(
        'station/<slug:code>/graph',
        station.ScatterView.as_view(),
        name='station-graph',
    ),

    path(
        'station/<slug:code>/graph-json',
        station.GraphViewJSON.as_view(),
        name='station-graph-json'
    ),
    path(
        'station/<slug:code>/json/',
        station.DetailViewJSON.as_view(),
        name='station-JSON'
    ),
    path('station/<slug:code>/heartbeat/',
        station.APIViewHeartbeat.as_view(),
        name='station-receive-heartbeat',
    ),
    path('station/<slug:code>/sighting/',
        station.APIViewSighting.as_view(),
        name='station-receive-sighting',
    ),
    path('stations/json/',
        station.ListViewJSON.as_view(),
        name='list-stations-JSON'
    ),

    path('subnetwork/<slug:code>/',
        subnetwork.SingleView.as_view(),
        name='subnetwork'
    ),

    path(
        'station/<slug:code>/heartbeats/<slug:id>/',
        heartbeat.SingleView.as_view(),
        name='heartbeat'
    ),
]

stations/models/country.py
import core.models


class Country(core.models.NamedModel):
    class Meta:
        verbose_name                = 'country'
        verbose_name_plural         = 'countries'

stations/models/heartbeat.py
import textwrap
import datetime
import pytz
import dotmap

from django.db import models
from django.db.models import F, Func, Aggregate, Prefetch, Avg, Min, Max
from django.db.models.functions import TruncMinute, Extract, Floor
from django.apps import apps
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import MinValueValidator, MaxValueValidator

from pprint import pprint as pp

import core.models


class HeartbeatManager(models.Manager):
    def get_queryset(self):
        return HeartbeatQuerySet(
            model=self.model,
            using=self._db,
            hints=self._hints,
        )

    def create_from_POST(self, code, **data):
        Station = apps.get_model('stations', 'Station')

        stateS = data['dome']['s']
        stateT = data['dome']['t']

        #pp(data)
        if stateS is None:
            cover_state = None
        else:
            if stateS[0] != '-':
                if stateS[1] != '-':
                    cover_state = Heartbeat.COVER_OPENING
                else:
                    cover_state = Heartbeat.COVER_CLOSING
            else:
                if stateS[14] != '-':
                    cover_state = Heartbeat.COVER_SAFETY
                else:
                    if stateS[2] != '-':
                        cover_state = Heartbeat.COVER_OPEN
                    elif stateS[3] != '-':
                        cover_state = Heartbeat.COVER_CLOSED
                    else:
                        cover_state = Heartbeat.COVER_PROBLEM

        try:
            station = Station.objects.get(code=code)
        except Station.DoesNotExist as e:
            raise Station.DoesNotExist(f"Station {code} does not exist")

        heartbeat = self.create(
            automatic                   = data['auto'],
            timestamp                   = data['time'],
            station                     = station,

            state                       = data['st'],
            status_string               = stateS,
            lens_heating                = (stateS[4] != '-') if stateS else None,
            camera_heating              = (stateS[5] != '-') if stateS else None,
            intensifier_active          = (stateS[6] != '-') if stateS else None,
            fan_active                  = (stateS[7] != '-') if stateS else None,

            rain_sensor_active          = (stateS[9] != '-') if stateS else None,
            light_sensor_active         = (stateS[10] != '-') if stateS else None,
            computer_power              = (stateS[11] != '-') if stateS else None,

            rain_emergency_closing      = (stateS[25] != '-') if stateS else None,

            temperature                 = None if stateT is None else stateT['t_sht'],
            t_lens                      = None if stateT is None else stateT['t_lens'],
            t_cpu                       = None if stateT is None else stateT['t_cpu'],
            humidity                    = None if stateT is None else stateT['h_sht'],

            cover_state                 = cover_state,
            cover_position              = None if data['dome']['z'] is None else data['dome']['z']['sp'],

            storage_primary_available   = data['disk']['prim']['a'],
            storage_primary_total       = data['disk']['prim']['t'],
            storage_permanent_available = data['disk']['perm']['a'],
            storage_permanent_total     = data['disk']['perm']['t'],
        )
        return heartbeat


class HeartbeatQuerySet(models.QuerySet):
    def for_station(self, station_code):
        return self.filter(station__code=station_code)

    def with_age(self):
        return self.annotate(
            age=datetime.datetime.now() - F('timestamp'),
        )

    def with_station(self):
        Station = apps.get_model('stations', 'Station')
        return self.prefetch_related(
            Prefetch(
                'station',
                queryset=Station.objects.with_subnetwork(),
            )
        )

    def for_floored_interval(self, start=None, end=None, interval=60):
        if end == None:
            end = datetime.datetime.now(tz=pytz.utc)
        if start == None:
            start = datetime.datetime.now(tz=pytz.utc) - datetime.timedelta(days=1)

        return self.filter(
                timestamp__range=(start, end)
            ).order_by(
                'timestamp'
            ).annotate(
                unix=Floor(Extract('timestamp', 'epoch') / interval) * interval,
                time=Func(F('unix'), function="TO_TIMESTAMP", output_field=models.DateTimeField()),
            )

    def as_graph(self, start=None, end=None, interval=60):
        return self.for_floored_interval(
                start, end, interval
            ).values(
                'time',
            ).annotate(
                t_env=Avg('temperature'),
                h_env=Avg('humidity'),
                t_len=Avg('t_lens'),
                t_CPU=Avg('t_cpu'),
                cover=Max('cover_state'),
            ).order_by()

    def as_sensors_graph(self, start=None, end=None, interval=60):
        return self.for_floored_interval(
                start, end, interval
            ).values(
                'time',
            ).annotate(
                t_env=Avg('temperature'),
                lh=BoolOr('lens_heating'),
                ch=BoolOr('camera_heating'),
                ii=BoolOr('intensifier_active'),
                fa=BoolOr('fan_active'),
                rs=BoolOr('rain_sensor_active'),
                ls=BoolOr('light_sensor_active'),
                cp=BoolOr('computer_power')
            ).order_by()

    def as_scatter(self, start=None, end=None):
        if end == None:
            end = datetime.datetime.now(tz=pytz.utc)
        if start == None:
            start = datetime.datetime.now(tz=pytz.utc) - datetime.timedelta(days=1)

        return self.filter(
            timestamp__range=(start, end)
        ).order_by(
            'timestamp'
        )


class Heartbeat(models.Model):
    class Meta:
        verbose_name                = 'heartbeat report'
        verbose_name_plural         = 'heartbeat reports'
        ordering                    = ['-timestamp']
        get_latest_by               = ['timestamp']
        indexes                     = [
                                        models.Index(fields=['timestamp', 'station']),
                                    ]

    STATE_DAYLIGHT = 'D'
    STATE_OBSERVING = 'O'
    STATE_NOT_OBSERVING = 'N'
    STATE_MANUAL = 'M'
    STATE_DOME_UNREACHABLE = 'U'
    STATE_RAIN_OR_HUMID = 'R'
    STATE_UNKNOWN = '?'
    STATES                          = [
                                        (STATE_OBSERVING, 'observing'),
                                        (STATE_NOT_OBSERVING, 'not observing'),
                                        (STATE_DAYLIGHT, 'day'),
                                        (STATE_MANUAL, 'manual'),
                                        (STATE_DOME_UNREACHABLE, 'dome unreachable'),
                                        (STATE_RAIN_OR_HUMID, 'rain or humidity'),
                                        (STATE_UNKNOWN, 'unknown'),
                                    ]

    COVER_OPEN = 'O'
    COVER_OPENING = 'o'
    COVER_CLOSED = 'C'
    COVER_CLOSING = 'c'
    COVER_PROBLEM = 'P'
    COVER_SAFETY = 'S'
    COVER_STATES                    = [
                                        (COVER_OPEN, 'open'),
                                        (COVER_OPENING, 'opening'),
                                        (COVER_CLOSED, 'closed'),
                                        (COVER_CLOSING, 'closing'),
                                        (COVER_PROBLEM, 'problem'),
                                        (COVER_SAFETY, 'safety'),
                                    ]

    objects                         = HeartbeatManager.from_queryset(HeartbeatQuerySet)()

    timestamp                       = models.DateTimeField(
                                        verbose_name        = 'timestamp',
                                        blank               = True,
                                        auto_now_add        = True,
                                    )
    received                        = models.DateTimeField(
                                        verbose_name        = 'received at',
                                        auto_now_add        = True,
                                    )

    station                         = models.ForeignKey(
                                        'Station',
                                        on_delete           = models.CASCADE,
                                        related_name        = 'heartbeats',
                                    )
    state                           = models.CharField(
                                        max_length          = 1,
                                        choices             = STATES,
                                        null                = True,
                                        blank               = True,
                                    )
    cover_state                     = models.CharField(
                                        max_length          = 1,
                                        choices             = COVER_STATES,
                                        null                = True,
                                        blank               = True,
                                    )

    # Device sensors
    status_string                   = models.CharField(null=True, blank=True, max_length=32)
    lens_heating                    = models.BooleanField(null=True, blank=True)
    camera_heating                  = models.BooleanField(null=True, blank=True)
    intensifier_active              = models.BooleanField(null=True, blank=True)

stations/models/status.py
from django.db import models


class Status(models.Model):
    class Meta:
        verbose_name = "status"
        verbose_name_plural = "statuses"
        ordering = ['-timestamp']
        get_latest_by = ['timestamp']

    STATUS_OK = 'O'
    STATUS_LOST = 'L'
    STATUS_OFF = 'F'
    STATUS_DISK_FULL = 'D'

    STATUS = [
        (STATUS_OK, 'online'),              # the station is working as intended
        (STATUS_OFF, 'turned off'),         # the station has been turned off intentionally
        (STATUS_LOST, 'lost contact'),      # the station does not send any reports
        (STATUS_DISK_FULL, 'disk full'),    # the station cannot observe due to a full disk
    ]

    timestamp = models.DateTimeField(verbose_name='timestamp')
    status = models.CharField(choices=STATUS)

stations/views.py
import datetime
import pytz

from pprint import pprint as pp

from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

from . import models

# Create your views here.

@login_required
def status(request):
    context = {
        'subnetworks': models.Subnetwork.objects.all(),
    }
    return render(request, 'stations/status.html', context)

def station(request, code):
    station = models.Station.objects.get(code = code)

    context = {
        'station': station,
        'lastDay': station.sighting_set.filter(timestamp__gte = datetime.datetime.now(pytz.utc) - datetime.timedelta(days = 1))
    }
    return render(request, 'stations/station.html', context)

def stationsJSON(request):
    return JsonResponse({station.id: station.asDict() for station in models.Station.objects.all()})

#@method_decorator(login_required, name = 'dispatch')
@method_decorator(csrf_exempt, name = 'dispatch')
class APIView(View):
    def get(self, request):
        return JsonResponse({'ok': 'OK'})
    

    def post(self, request):
        print(f"{'*' * 20} Incoming status report {'*' * 20}")

        pp(request.body)

        return HttpResponse('Status update received', status = 201)

stations/views/heartbeat.py
import logging
import core.views

from stations.models import Heartbeat

log = logging.getLogger(__name__)


class SingleView(core.views.LoginDetailView):
    model           = Heartbeat
    slug_field      = 'id'
    slug_url_kwarg  = 'id'
    template_name   = 'stations/heartbeat.html'
    context_object_name = 'heartbeat'

stations/views/subnetwork.py
import datetime
import pytz

from core.views import LoginDetailView, LoginListView
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page

from stations.models import Subnetwork


#@method_decorator(cache_page(5), name='dispatch')
class StatusView(LoginListView):
    model               = Subnetwork
    context_object_name = 'subnetworks'
    template_name       = 'stations/status.html'

    def get_queryset(self):
        return Subnetwork.objects.with_full_stations().with_count().order_by('founded')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = datetime.datetime.now(tz=pytz.utc)
        return context


class SingleView(LoginDetailView):
    model           = Subnetwork
    slug_field      = 'code'
    slug_url_kwarg  = 'code'
    template_name   = 'stations/subnetwork.html'

stations/templates/stations/heartbeat.html
{% extends 'core/base.html' %}
{% load static tz quantities %}

{% block pagetitle %}
    <h2>Heartbeat</h2>
    <div class="controls">
        <a href="{% url 'admin:stations_heartbeat_change' heartbeat.id %}">
            <img class="" src="{% static 'pictures/edit.png' %}" />
        </a>
    </div>
{% endblock pagetitle %}

{% block page %}
    <p>
        From station <a href="{{ heartbeat.station.get_absolute_url }}">{{ heartbeat.station.name }}</a> (<span class="bold">{{ heartbeat.station.code }}</span>),
        received at {{ heartbeat.timestamp }}
    </p>

    <h3>Properties</h3>
        <table>
            {% include "stations/heartbeat/thead.html" %}
            <tbody>
                <tr>
                    <td class="data c timestamp">
                        {{ heartbeat.timestamp|date:"Y-m-d H:i:s" }}
                    </td>
                    {% include "stations/heartbeat/tr.html" %}
                </tr>
            </tbody>
        </table>

{% endblock page %}

stations/templates/stations/log.html
{% load station_tags %}

<h3>Station log</h3>
<table>
    <thead>
        <tr>
            <th>date</th>
            <th>author</th>
            <th>entry</th>
        </tr>
    </thead>
    <tbody>
        {% for entry in station.log_entries.all|slice:":10" %}
            <tr>
                <td class="data timestamp">{{ entry.created|date:"Y-m-d H:i" }}</td>
                <td class="data name">{{ entry.author|default_if_none:"&mdash;" }}</td>
                <td>{{ entry.text }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="2" class="empty">
                    There are no log entries for this station.
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

stations/templates/stations/sightings.html
{% load meteor_tags %}
{% load station_tags %}

<h3>Sightings ({{ station.sightings.count }} total)</h3>
<table>
    <thead>
        <tr>
            <th>timestamp</th>
            <th>ago</th>
            <th>magnitude</th>
        </tr>
    </thead>
    {% for sighting in station.recent_sightings %}
        <tr>
            <td class="data time">
                <a href="{% url 'sighting' id=sighting.id %}">{{ sighting.timestamp }}</a>
            </td>
            <td class="data">
                {{ sighting.timestamp|since_date_time }}
            </td>
            <td class="data magnitude">
                {{ sighting.magnitude|magnitude }}
            </td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="2" class="empty">
                There are no recorded sightings from this station.
            </td>
        </tr>
    {% endfor %}
</table>

stations/templates/stations/station-heartbeats.html
{% load station_tags %}

<h3>Status ({{ station.heartbeats.count }} heartbeats total)</h3>
<table>
    <thead>
        <tr>
            <th>timestamp</th>
            <th>status</th>
            <th>lid</th>
            <th>heating</th>
            <th><abbr title="temperature">T</abbr></th>
            <th><abbr title="atmospheric pressure">p</abbr></th>
            <th><abbr title="relative humidity">RH</abbr></th>
        </tr>
    </thead>
    {% for heartbeat in station.recent_heartbeats %}
        <tr>
            <td class="data timestamp">{{ heartbeat.timestamp|date:"Y-m-d H:i:s" }}</td>
            <td class="data status">{{ heartbeat.get_status_display }}</td>
            <td class="data status">{{ heartbeat.get_lid_display }}</td>
            <td class="data status">{{ heartbeat.get_heating_display }}</td>
            <td class="data">{{ heartbeat.temperature|temperature }}</td>
            <td class="data">{{ heartbeat.pressure|pressure }}</td>
            <td class="data">{{ heartbeat.humidity|humidity }}</td>
        </tr>
    {% empty %}
        <tr>
            <td class="data c empty" colspan="7">There are no heartbeats for this station.</td>
        </tr>
    {% endfor %}
</table>

stations/templates/stations/station-log.html
{% load station_tags %}

<h3>Station log</h3>
<table>
    <thead>
        <tr>
            <th>date</th>
            <th>author</th>
            <th>entry</th>
        </tr>
    </thead>
    <tbody>
        {% for entry in station.log_entries.all|slice:":10" %}
            <tr>
                <td class="data timestamp">{{ entry.created|date:"Y-m-d H:i:s" }}</td>
                <td class="data name">{{ entry.author|default_if_none:"&mdash;" }}</td>
                <td class="data text">{{ entry.text }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3" class="data c empty">
                    There are no log entries for this station.
                </td>
            </tr>
        {% endfor %}
            <tr>
                <td colspan="3" class="c admin"><a href="{% url 'admin:stations_logentry_add' %}?station={{ station.id }}&author={{ request.user.id }}">+ add new log entry</a></td>
            </tr>
    </tbody>
</table>

stations/templates/stations/station-sightings.html
{% load meteor_tags %}
{% load station_tags %}

<h3>Sightings ({{ station.sightings.count }} total)</h3>
<table>
    <thead>
        <tr>
            <th>timestamp</th>
            <th>ago</th>
            <th>magnitude</th>
        </tr>
    </thead>
    {% for sighting in station.recent_sightings %}
        <tr>
            <td class="data time">
                <a href="{% url 'sighting' id=sighting.id %}">{{ sighting.timestamp }}</a>
            </td>
            <td class="data">
                {{ sighting.timestamp|since_date_time }}
            </td>
            <td class="data magnitude">
                {{ sighting.magnitude|magnitude }}
            </td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="3" class="data c empty">
                There are no recorded sightings from this station.
            </td>
        </tr>
    {% endfor %}
</table>

stations/templates/stations/station-sky.html
{% load station_tags %}

<h3>Sky at this moment</h3>
<table>
    <thead>
        <tr>
            <th>object</th>
            <th colspan="2">altitude</th>
            <th colspan="2">azimuth</th>
            <th>magnitude</th>
        </tr>
    </thead>
    {% with sun=station.sun_position %}
        <tr>
            <td>Sun</td>
            <td class="data sun" style="background-color: {{ sun.alt|altitude_colour_back }}; color: {{ sun.alt|altitude_colour_front }};">
                <span class="suninfo standalone">
                    {{ sun.alt|floatformat:1 }}°
                </span>
            </td>
            <td class="data arrow" style="background-color: {{ sun.alt|altitude_colour_back }}; color: {{ sun.alt|altitude_colour_front }};">
                <span class="arrow" style="transform: rotate({{ sun.alt|multiply:-1 }}deg);">&#8594;</span>
            </td>
            <td class="data sun">
                <span>{{ sun.az|floatformat:1 }}°</span>
            </td>
            <td class="data arrow">
                <span class="arrow" style="transform: rotate({{ sun.az|add:-90 }}deg);">&#8594;</span>
            </td>
            <td class="data sun">
                -26.74<sup>m</sup>
            </td>
        </tr>
    {% endwith %}
    {% with moon=station.moon_position %}
        <tr>
            <td>Moon</td>
            <td class="data moon" style="background-color: {{ moon.alt|altitude_colour_back }}; color: {{ moon.alt|altitude_colour_front }};">
                <span class="mooninfo standalone">
                    {{ moon.alt|floatformat:1 }}°
                </span>
            </td>
            <td class="data arrow" style="background-color: {{ moon.alt|altitude_colour_back }}; color: {{ moon.alt|altitude_colour_front }};">
                <span class="arrow" style="transform: rotate({{ moon.alt|multiply:-1 }}deg);">&#8594;</span>
            </td>
            <td class="data moon">
                <span>{{ moon.az|floatformat:1 }}°</span>
            </td>
            <td class="data arrow">
                <span class="arrow" style="transform: rotate({{ moon.az|add:-90 }}deg);">&#8594;</span>
            </td>
            <td class="data moon">
                <span class="empty">not implemented</span>
            </td>
        </tr>
    {% endwith %}

</table>

stations/templates/stations/station.html
{% extends 'core/base.html' %}
{% load static %}
{% load tz %}
{% load station_tags %}
{% load meteor_tags %}

{% block pagetitle %}
    <h2>Station <span class="bold">{{ station.name }}</span> (<span class="bold">{{ station.code }}</span>)</h2>
    <div class="controls">
        <a href="{% url 'admin:stations_station_change' station.id %}">
            <img class="" src="{% static 'pictures/edit.png' %}" />
        </a>
    </div>
{% endblock pagetitle %}

{% block headextra %}
    <link rel="stylesheet" type="text/css" href="{% static "js/ol.css" %}" />
    <script src="{% static "js/ol.js" %}"></script>
    <script src="{% static "meteors/js/map.js" %}"></script>
{% endblock headextra %}

{% block page %}
    <div class="inner">
        <div class="info">
            <h3>Station info</h3>
                <p>{{ station.address }}</p>
                <p id="location">{{ station.location }}</p>
                <p id="localtime">Local time: <span class="b">{% timezone station.timezone %}{% now "Y-m-d H:i:s" %}{% endtimezone %}</span></p>
                {% with status=station.current_status %}
                    <p id="status">{{ status.short }}</p>
                {% endwith %}

            {% include "stations/station/sky.html" %}
            {% include "stations/station/sightings.html" %}
            {% include "stations/station/heartbeats.html" %}
            {% include "stations/station/log.html" %}
        </div>

        <div class="preview">
            <div id="map" class="map"> </div>
        </div>
    </div>

{% endblock page %}

stations/templates/stations/status.html
{% extends 'core/base.html' %}
{% load tz quantities styles %}

{% block pagetitle %}
<h2>AMOS network status</h2>
{% endblock pagetitle %}

{% block page %}
    <p>
        It is {{ now }} ({% timezone "Europe/Bratislava" %} {{ now }} {% endtimezone %})
    </p>

    <table class="full-width">
        <thead>
            <tr>
                <th>subnetwork</th>
                <th>code</th>
                <th>name</th>
                <th>enabled</th>
                <th colspan="3">status</th>
                <th>local time</th>
                <th colspan="2">&#x2600;</th>
                <th colspan="2">last sighting</th>
            </tr>
        </thead>
        {% for subnetwork in subnetworks %}
            {% for station in subnetwork.stations_full %}
                <tr>
                    {% if forloop.first %}
                        <th class="subgroup" rowspan="{{ subnetwork.station_count }}">
                            <a href="{{ subnetwork.get_absolute_url }}">{{ subnetwork.name }} ({{ subnetwork.code }})</a>
                        </th>
                    {% endif %}
                    {% with sun=station.sun_position heartbeat=station.last_heartbeat.0 status=station.get_current_status last_sighting=station.last_sighting.0 %}
                        <td class="data r">
                            {{ station.code }}
                        </td>

                        <td class="data l">
                            <a href="{{ station.get_absolute_url }}">{{ station.name }}</a>
                        </td>

                        <td class="status c">
                            {{ station.on|trivalue }}
                        </td>
                        <td class="status c">
                            <abbr class="status {{ status.code }}" title="{{ status.get_description }}">
                                {{ status.short }}
                            </abbr>
                        </td>
                        <td class="status c">
                            {% if heartbeat %}
                                {% if status.code == 'ok' %}
                                    {{ heartbeat.get_cover_state_display }}
                                {% else %}
                                    ?
                                {% endif %}
                            {% else %}
                                &mdash;
                            {% endif %}
                        </td>
                        <td class="status r">
                            {% if heartbeat %}
                                <a href="{{ heartbeat.get_absolute_url }}">
                                    <abbr title="{{ heartbeat.timestamp }}">{{ heartbeat.timestamp|since_date_time|default:"&mdash;" }}</abbr>
                                </a>
                            {% else %}
                                &mdash;
                            {% endif %}
                        </td>

                        <td id="{{ station.code }}-localtime" class="time c">
                            {% timezone station.timezone %}
                                <abbr title="{% now "Y-m-d" %}">{% now "H:i" %}</abbr>
                            {% endtimezone %}
                        </td>

                        <td id="{{ station.code }}-sunalt"
                            class="data angle altitude"
                            style="background-color: {{ sun.alt|altitude_colour_back }}; color: {{ sun.alt|altitude_colour_front }};">
                            {{ sun.alt|floatformat:1 }}°
                            <span class="sun arrow" style="transform: rotate({{ sun.alt|multiply:-1 }}deg);">&#8594;</span>
                        </td>
                        <td id="{{ station.code }}-sunaz" class="data angle azimuth">
                            {{ sun.az|floatformat:1 }}°
                            <span class="sun arrow" style="transform: rotate({{ sun.az|add:-90 }}deg);">&#8594;</span>
                        </td>

                        <td class="time c">
                            {% if last_sighting %}
                                <a href="{{ last_sighting.get_absolute_url }}">{{ last_sighting.timestamp|date:"Y-m-d H:i:s" }}</a>
                            {% else %}
                                <span class="empty">no sightings</span>
                            {% endif %}
                        </td>
                        <td class="time r">
                            {% if last_sighting %}
                                {{ last_sighting.timestamp|since_date_time }}
                            {% else %}
                                <span class="empty">never</span>
                            {% endif %}
                        </td>
                    {% endwith %}
                </tr>
            {% empty %}
                <tr>
                    <th class="subgroup">
                        <a href="{{ subnetwork.get_absolute_url }}">{{ subnetwork.name }} ({{ subnetwork.code }})</a>
                    </th>
                    <td colspan="10" class="data c empty">No stations are defined in this subnetwork.</td>
                </tr>
            {% endfor %}
            {% if not forloop.last %}
                <tr class="spacer"><td colspan="12"></td></tr>
            {% endif %}
        {% endfor %}
    </table>

    <h3>Sun info</h3>
    <table>
        <tr>
            <th>Property</th>
            <th>Value</th>
        </tr>
        <tr>
            <td>Solar longitude &#955;<sub>&#9737;</sub></td>
            <td class="data r">{{ now|solar_longitude|angle }}</td>
        </tr>
        <tr>
            <td>Solar declination &#948;<sub>&#9737;</sub></td>
            <td class="data r">{{ now|solar_declination|angle }}</td>
        </tr>
    </table>
{% endblock page %}